### ISSUE TITLE
ARTOP 4.12 반영 검토

### ISSUE THREAD

**Issue by sykim-rtst** [sykim-rtst/rasp-tool#3]
최근에 ARTOP 4.12 버전이 릴리즈되어서 이를 반영하는 것이 필요합니다. 이와 관련하여 현재 개발 중인 plugin에 반영할 사항이 있는지 검토하여 반영 부탁드립니다.

**Comment by sykim-rtst** [comment]
@ysyang-rtst 이 이슈도 #4 PR에서 해결된 것인 아닌가 싶은데.. 확인 부탁드립니다.

**Comment by sykim-rtst** [comment]
해당 이슈는 PR(#4)에서 해결되지 않은 것인가요?
Commit에는 4.12라는 언급이 있는데, PR 제목에는 4.10으로 써있어서 헷갈립니다.
확인 부탁드립니다.

**Comment by ysyang-rtst** [comment]
본래 의도는 아래 2가지를 각각 PR하여 적용하는 것이었는데, 함께 처리되었습니다. 

1. 통합 repo (4.10) 관련
2. 4.12 포팅 관련

본 이슈(#3 ARTOP 4.12 반영 검토)도 Close하겠습니다.
